### ISSUE TITLE
Agregar comando validación usuario.

### ISSUE THREAD

**Issue by JPYamamoto** [JPYamamoto/private_channels_discord_bot#1]
Agregar un comando, `!usuario <email>`.
Al ejecutar este comando, el bot debe:
- Leer el correo electrónico ingresado por el usuario.
- Borrar el mensaje para evitar que otros usuarios vean los correos electrónicos.
- Identificar en qué talleres está registrado el usuario (desde un csv, con formato por definir. Se aceptan sugerencias).
- Agregar al usuario al canal correspondiente al taller.

**Comment by Manu-Mx** [comment]
https://github.com/Manu-Mx/Bot_Discord/tree/main/src

Aquí va el comando funcionando.

- Dentro de la función "usuario(ctx, email)" hay que cambiar  la condicional del primer if ya que tiene que detectar si el campo es vacio y mande mensaje que tiene que poner un correo.
- Cambiar la condicional del 'elif' de la linea 37 para que arroje un mensaje si  no pudo encontrar el correo.
- Dentro del if de la linea 29, despues de encontrar al usuario, sería quitar/cambiar el comando para que le asigne el rol
